wagtailvideos/urls.py
from django.urls import path, re_path

from wagtailvideos.views import multiple, videos

app_name = 'wagtailvideos'

urlpatterns = [
    path('add/', videos.add, name='add'),
    re_path(r'^usage/(\d+)/$', videos.usage, name='video_usage'),

    path("multiple/add/", multiple.AddView.as_view(), name="add_multiple"),
    path("multiple/<int:video_id>/", multiple.EditView.as_view(), name="edit_multiple"),
    path(
        "multiple/create_from_uploaded_image/<int:uploaded_file_id>/",
        multiple.CreateFromUploadedVideoView.as_view(),
        name="create_multiple_from_uploaded_image",
    ),
    path(
        "multiple/<int:video_id>/delete/",
        multiple.DeleteView.as_view(),
        name="delete_multiple",
    ),
    path(
        "multiple/delete_upload/<int:uploaded_file_id>/",
        multiple.DeleteUploadView.as_view(),
        name="delete_upload_multiple",
    ),

    re_path(r'^(\d+)/delete/$', videos.delete, name='delete'),
    re_path(r'^(\d+)/create_transcode/$', videos.create_transcode, name='create_transcode'),
    re_path(r'^(\d+)/$', videos.edit, name='edit'),
    path('', videos.IndexView.as_view(), name='index'),
    path("results/", videos.IndexView.as_view(results_only=True), name="index_results"),
]

wagtailvideos/views/chooser.py
from django.conf import settings
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import View
from wagtail.admin.auth import PermissionPolicyChecker
from wagtail.admin.models import popular_tags_for_model
from wagtail.admin.views.generic.chooser import (
    BaseChooseView, ChooseResultsViewMixin, ChooseViewMixin,
    ChosenResponseMixin, ChosenViewMixin, CreateViewMixin, CreationFormMixin)
from wagtail.admin.viewsets.chooser import ChooserViewSet

from wagtailvideos import get_video_model
from wagtailvideos.forms import get_video_form
from wagtailvideos.permissions import permission_policy

permission_checker = PermissionPolicyChecker(permission_policy)


class VideoChosenResponseMixin(ChosenResponseMixin):
    def get_chosen_response_data(self, video):
        response_data = super().get_chosen_response_data(video)
        response_data["preview"] = {
            "url": video.thumbnail.url if video.thumbnail else "",
            "width": 165,
            "height": 165,
        }
        return response_data


class VideoCreationFormMixin(CreationFormMixin):
    creation_tab_id = "upload"
    create_action_label = _("Upload")
    create_action_clicked_label = _("Uploading…")
    permission_policy = permission_policy

    def get_creation_form_class(self):
        return get_video_form(self.model)

    def get_creation_form_kwargs(self):
        kwargs = super().get_creation_form_kwargs()
        if self.request.method in ("POST", "PUT"):
            kwargs["instance"] = self.model(uploaded_by_user=self.request.user)
        return kwargs


class BaseVideoChooseView(BaseChooseView):
    template_name = "wagtailvideos/chooser/chooser.html"
    results_template_name = "wagtailvideos/chooser/results.html"
    per_page = getattr(settings, "WAGTAILVIDEOS_CHOOSER_PAGE_SIZE", 12)
    ordering = "-created_at"

    def get_object_list(self):
        return (
            permission_policy.instances_user_has_any_permission_for(
                self.request.user, ["choose"]
            )
            .select_related("collection")
        )

    def filter_object_list(self, objects):
        tag_name = self.request.GET.get("tag")
        if tag_name:
            objects = objects.filter(tags__name=tag_name)
        return super().filter_object_list(objects)

    def get_filter_form(self):
        FilterForm = self.get_filter_form_class()
        return FilterForm(self.request.GET, collections=self.collections)

    @cached_property
    def collections(self):
        collections = self.permission_policy.collections_user_has_permission_for(
            self.request.user, "choose"
        )
        if len(collections) < 2:
            return None

        return collections

    def get(self, request):
        self.model = get_video_model()
        return super().get(request)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "collections": self.collections,
            }
        )
        return context


class VideoChooseViewMixin(ChooseViewMixin):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["popular_tags"] = popular_tags_for_model(self.model)
        return context

    def get_response_json_data(self):
        json_data = super().get_response_json_data()
        json_data["tag_autocomplete_url"] = reverse("wagtailadmin_tag_autocomplete")
        return json_data


class VideoChooseView(
    VideoChooseViewMixin, VideoCreationFormMixin, BaseVideoChooseView
):
    pass


class VideoChooseResultsView(
    ChooseResultsViewMixin, VideoCreationFormMixin, BaseVideoChooseView
):
    pass


class VideoChosenView(ChosenViewMixin, VideoChosenResponseMixin, View):
    def get(self, request, *args, pk, **kwargs):
        self.model = get_video_model()
        return super().get(request, *args, pk, **kwargs)


class VideoUploadViewMixin(CreateViewMixin):
    def get(self, request):
        self.model = get_video_model()
        return super().get(request)

    def post(self, request):
        self.model = get_video_model()
        self.form = self.get_creation_form()

        if self.form.is_valid():
            image = self.save_form(self.form)

            # not specifying a format; return the image details now
            return self.get_chosen_response(image)

        else:  # form is invalid
            return self.get_reshow_creation_form_response()


class VideoUploadView(
    VideoUploadViewMixin, VideoCreationFormMixin, VideoChosenResponseMixin, View
):
    pass


class VideoChooserViewSet(ChooserViewSet):
    choose_view_class = VideoChooseView
    choose_results_view_class = VideoChooseResultsView
    chosen_view_class = VideoChosenView
    create_view_class = VideoUploadView
    permission_policy = permission_policy
    register_widget = False

    icon = "media"
    choose_one_text = _("Choose a video")
    create_action_label = _("Upload")
    create_action_clicked_label = _("Uploading…")


viewset = VideoChooserViewSet(
    "wagtailvideos_chooser",
    model=get_video_model(),
    url_prefix="videos/chooser",
)

wagtailvideos/views/multiple.py
import os

from wagtail.admin.auth import PermissionPolicyChecker
from wagtail.admin.views.generic.multiple_upload import AddView as BaseAddView
from wagtail.admin.views.generic.multiple_upload import \
    CreateFromUploadView as BaseCreateFromUploadView
from wagtail.admin.views.generic.multiple_upload import \
    DeleteUploadView as BaseDeleteUploadView
from wagtail.admin.views.generic.multiple_upload import \
    DeleteView as BaseDeleteView
from wagtail.admin.views.generic.multiple_upload import \
    EditView as BaseEditView

from wagtailvideos import get_video_model
from wagtailvideos.forms import get_video_form
from wagtailvideos.permissions import permission_policy

permission_checker = PermissionPolicyChecker(permission_policy)


def get_video_edit_form(video_model):
    VideoForm = get_video_form(video_model)

    class VideoEditForm(VideoForm):
        class Meta(VideoForm.Meta):
            model = video_model
            exclude = (
                'file',
            )

    return VideoEditForm


class AddView(BaseAddView):
    permission_policy = permission_policy
    template_name = 'wagtailvideos/multiple/add.html'
    edit_form_template_name = 'wagtailvideos/multiple/edit_form.html'

    edit_object_url_name = "wagtailvideos:edit_multiple"
    delete_object_url_name = "wagtailvideos:delete_multiple"
    edit_object_form_prefix = "video"
    context_object_name = "video"
    context_object_id_name = "video_id"

    edit_upload_url_name = "wagtailvideos:create_multiple_from_uploaded_image"
    delete_upload_url_name = "wagtailvideos:delete_upload_multiple"
    edit_upload_form_prefix = "uploaded-video"
    context_upload_name = "uploaded_video"
    context_upload_id_name = "uploaded_file_id"

    def get_model(self):
        return get_video_model()

    def get_upload_form_class(self):
        return get_video_form(self.model)

    def get_edit_form_class(self):
        return get_video_edit_form(self.model)

    def save_object(self, form):
        video = form.save(commit=False)
        video.uploaded_by_user = self.request.user
        video.save()
        return video

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update(
            {
                "max_filesize": self.form.fields["file"].max_upload_size,
                "max_title_length": self.form.fields["title"].max_length,
                "error_max_file_size": self.form.fields["file"].error_messages[
                    "file_too_large_unknown_size"
                ],
                "error_accepted_file_types": self.form.fields["file"].error_messages[
                    "invalid_video_format"
                ],
            }
        )

        return context


class EditView(BaseEditView):
    permission_policy = permission_policy
    pk_url_kwarg = "video_id"
    edit_object_form_prefix = "video"
    context_object_name = "video"
    context_object_id_name = "video_id"
    edit_object_url_name = "wagtailvideos:edit_multiple"
    delete_object_url_name = "wagtailvideos:delete_multiple"

    def get_model(self):
        return get_video_model()

    def get_edit_form_class(self):
        return get_video_edit_form(self.model)


class DeleteView(BaseDeleteView):
    permission_policy = permission_policy
    pk_url_kwarg = "video_id"
    context_object_id_name = "video_id"

    def get_model(self):
        return get_video_model()


class CreateFromUploadedVideoView(BaseCreateFromUploadView):
    edit_upload_url_name = "wagtailvideos:create_multiple_from_uploaded_image"
    delete_upload_url_name = "wagtailvideos:delete_upload_multiple"
    upload_pk_url_kwarg = "uploaded_file_id"
    edit_upload_form_prefix = "uploaded-video"
    context_object_id_name = "video_id"
    context_upload_name = "uploaded_video"

    def get_model(self):
        return get_video_model()

    def get_edit_form_class(self):
        return get_video_edit_form(self.model)

    def save_object(self, form):
        #  See wagtailimages.views.multiple.CreateFromUploadedImageView.save_object
        self.object.file.save(
            os.path.basename(self.upload.file.name), self.upload.file.file, save=False
        )
        self.object.uploaded_by_user = self.request.user

        self.object._set_image_file_metadata()

        form.save()


class DeleteUploadView(BaseDeleteUploadView):
    upload_pk_url_kwarg = "uploaded_file_id"

    def get_model(self):
        return get_video_model()

wagtailvideos/views/videos.py
from django.conf import settings
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.decorators.http import require_POST
from wagtail.admin import messages
from wagtail.admin.auth import PermissionPolicyChecker
from wagtail.admin.filters import BaseMediaFilterSet
from wagtail.admin.views import generic
from wagtail.search.backends import get_search_backends
from wagtail_modeladmin.helpers import AdminURLHelper

from wagtailvideos import (
    get_transcoder_backend, get_video_model, is_modeladmin_installed)
from wagtailvideos.forms import VideoTranscodeAdminForm, get_video_form
from wagtailvideos.permissions import permission_policy

permission_checker = PermissionPolicyChecker(permission_policy)


Video = get_video_model()


class VideoFilterSet(BaseMediaFilterSet):
    permission_policy = permission_policy

    class Meta:
        model = Video
        fields = []


class IndexView(generic.IndexView):
    context_object_name = "videos"
    model = Video
    filterset_class = VideoFilterSet
    permission_policy = permission_policy
    any_permission_required = ['add', 'change', 'delete']
    header_icon = 'media'
    template_name = 'wagtailvideos/videos/index.html'
    results_template_name = 'wagtailvideos/videos/results.html'
    _show_breadcrumbs = True
    add_url_name = "wagtailvideos:add_multiple"
    edit_url_name = "wagtailvideos:edit"
    index_results_url_name = 'wagtailvideos:index_results'
    add_item_label = "Add a video"

    def get_breadcrumbs_items(self):
        return self.breadcrumbs_items + [
            {"url": "", "label": "Videos"},
        ]

    def get_filterset_kwargs(self):
        kwargs = super().get_filterset_kwargs()
        kwargs["is_searching"] = self.is_searching
        return kwargs

    def get_paginate_by(self, queryset):
        return 32  # 4 x 8


@permission_checker.require('change')
def edit(request, video_id):
    Video = get_video_model()
    VideoForm = get_video_form(Video)
    video = get_object_or_404(Video, id=video_id)

    if request.POST:
        original_file = video.file
        form = VideoForm(request.POST, request.FILES, instance=video)
        if form.is_valid():
            if 'file' in form.changed_data:
                # if providing a new video file, delete the old one and all renditions.
                # NB Doing this via original_file.delete() clears the file field,
                # which definitely isn't what we want...
                original_file.storage.delete(original_file.name)

                # Set new video file size
                video.file_size = video.file.size

            video = form.save()
            video.save()

            # Reindex the video to make sure all tags are indexed
            for backend in get_search_backends():
                backend.add(video)

            messages.success(request, _("Video '{0}' updated.").format(video.title))
        else:
            messages.error(request, _("The video could not be saved due to errors."))
    else:
        form = VideoForm(instance=video)

    if not video._meta.get_field('file').storage.exists(video.file.name):
        # Give error if video file doesn't exist
        messages.error(request, _(
            "The source video file could not be found. Please change the source or delete the video."
        ).format(video.title), buttons=[
            messages.button(reverse('wagtailvideos:delete', args=(video.id,)), _('Delete'))
        ])
    if is_modeladmin_installed():
        url_helper = AdminURLHelper(Video.get_track_listing_model())
        if hasattr(video, 'track_listing'):
            action_url = url_helper.get_action_url('edit', instance_pk=video.track_listing.pk)
        else:
            action_url = url_helper.create_url
    else:
        action_url = ''

    return render(request, "wagtailvideos/videos/edit.html", {
        'video': video,
        'form': form,
        'filesize': video.get_file_size(),
        'transcoder_installed': get_transcoder_backend().installed(),
        'transcoder_enabled': not getattr(settings, 'WAGTAIL_VIDEOS_DISABLE_TRANSCODE', False),
        'transcodes': video.transcodes.all(),
        'transcode_form': VideoTranscodeAdminForm(video=video),
        'tracks_action_url': action_url,
        'user_can_delete': permission_policy.user_has_permission_for_instance(request.user, 'delete', video)
    })


@require_POST
def create_transcode(request, video_id):
    video = get_object_or_404(get_video_model(), id=video_id)
    transcode_form = VideoTranscodeAdminForm(data=request.POST, video=video)

    if transcode_form.is_valid():
        transcode_form.save()
    return redirect('wagtailvideos:edit', video_id)


@permission_checker.require('delete')
def delete(request, video_id):
    video = get_object_or_404(get_video_model(), id=video_id)

    if request.POST:
        video.delete()
        messages.success(request, _("Video '{0}' deleted.").format(video.title))
        return redirect('wagtailvideos:index')

    return render(request, "wagtailvideos/videos/confirm_delete.html", {
        'video': video,
    })


@permission_checker.require('add')
def add(request):
    Video = get_video_model()
    VideoForm = get_video_form(Video)

    if request.POST:
        video = Video(uploaded_by_user=request.user)
        form = VideoForm(request.POST, request.FILES, instance=video, user=request.user)
        if form.is_valid():
            # Save
            video = form.save(commit=False)
            video.file_size = video.file.size
            video.save()

            # Success! Send back an edit form
            for backend in get_search_backends():
                backend.add(video)

            messages.success(request, _("Video '{0}' added.").format(video.title), buttons=[
                messages.button(reverse('wagtailvideos:edit', args=(video.id,)), _('Edit'))
            ])
            return redirect('wagtailvideos:index')
        else:
            messages.error(request, _("The video could not be created due to errors."))
    else:
        form = VideoForm(user=request.user)

    return render(request, "wagtailvideos/videos/add.html", {
        'form': form,
    })


def usage(request, video_id):
    video = get_object_or_404(get_video_model(), id=video_id)

    paginator = Paginator(video.get_usage(), per_page=12)
    page = paginator.get_page(request.GET.get('p'))

    return render(request, "wagtailvideos/videos/usage.html", {
        'video': video,
        'used_by': page
    })

wagtailvideos/templates/wagtailvideos/videos/_file_field.html
{% extends "wagtailadmin/shared/field.html" %}
{% load i18n %}
{% block form_field %}
    <a href="{{ video.url }}" class="icon icon-media">{{ video.filename }}</a><br /><br />

    {% trans "Change video file:" %}
    {{ field }}
{% endblock %}

wagtailvideos/templates/wagtailvideos/videos/_file_field_as_li.html
{% load wagtailadmin_tags %}
<li class="{% if field.field.required %}required{% endif %} {{ wrapper_classes }} {{ li_classes }} {% if field.errors %}error{% endif %}">
    {% include "wagtailvideos/videos/_file_field.html" %}
</li>

wagtailvideos/templates/wagtailvideos/videos/add.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% trans "Add a video" %}{% endblock %}

{% block extra_js %}
	{{ block.super }}
	{% url 'wagtailadmin_tag_autocomplete' as autocomplete_url %}
	<script>
		$(function () {
			$("#id_tags").tagit({
				autocomplete: { source: "{{ autocomplete_url|addslashes }}" },
			});
		});
	</script>
{% endblock %}

{% block content %}
	{% trans "Add video" as add_str %}
	{% include "wagtailadmin/shared/header.html" with title=add_str icon="media" %}

	<div class="nice-padding">
		<form action="{% url 'wagtailvideos:add' %}" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<ul class="fields">
				{% for field in form %}
					{% if field.is_hidden %}
						{{ field }}
					{% else %}
						<li>{% include "wagtailadmin/shared/field.html" with field=field %}</li>
					{% endif %}
				{% endfor %}
				<li><input class="button" type="submit" value="{% trans 'Save' %}" /></li>
			</ul>
		</form>
	</div>
{% endblock %}

wagtailvideos/templates/wagtailvideos/videos/confirm_delete.html
{% extends "wagtailadmin/base.html" %}
{% load wagtailvideos_tags %}
{% load i18n %}
{% block titletag %}{% trans "Delete video" %}{% endblock %}

{% block content %}
    {% trans "Delete video" as del_str %}
    {% include "wagtailadmin/shared/header.html" with title=del_str icon="media" %}

    <div class="row row-flush nice-padding">
        <div class="col6">
            {% video video controls style=max-width:100% %}
        </div>
        <div class="col6">
            <p>{% trans "Are you sure you want to delete this video?" %}</p>
            <form action="{% url 'wagtailvideos:delete' video.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" class="button serious" value="{% trans 'Yes, delete' %}" />
            </form>
        </div>
    </div>
{% endblock %}

wagtailvideos/templates/wagtailvideos/videos/edit.html
{% extends "wagtailadmin/base.html" %}

{% load static wagtailadmin_tags i18n wagtailvideos_tags %}

{% block titletag %}{% blocktrans with title=video.title %}Editing video {{ title }}{% endblocktrans %}{% endblock %}

{% block extra_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'wagtailvideos/css/edit-video.css' %}" type="text/css" /> {% endblock %}

{% block content %}
{% trans "Editing" as editing_str %}

{% include "wagtailadmin/shared/header.html" with title=editing_str subtitle=video.title icon="media" %}

<div class="row row-flush nice-padding">
    <div class="col6">
        <form action="{% url 'wagtailvideos:edit' video.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <ul class="fields">
                {% for field in form %}
                  {% if field.name == 'file' %}
                    {% include "wagtailvideos/videos/_file_field_as_li.html"  with li_classes="label-above label-uppercase" %}
                  {% elif field.is_hidden %}
                    {{ field }}
                  {% else %}
                    <li>{% include "wagtailadmin/shared/field.html" with li_classes="label-above label-uppercase" %}</li>
                  {% endif %}
                {% endfor %}
                <li>
                    <input type="submit" class="button" value="{% trans 'Save' %}" />
                    {% if user_can_delete %}
                        <a href="{% url 'wagtailvideos:delete' video.id %}" class="button button-secondary no">{% trans "Delete video" %}</a>
                    {% endif %}
                </li>
            </ul>
        </form>
    </div>
    <div class="col6">
        <div class="row">
            <div class="col10 divider-after">
                {% video video controls style=max-width:100%;width:100%;height:auto; %}
            </div>
            <div class="col2">
                <dl style="margin-top: 0;">
                    {% if video.thumbnail %}
                    <dt>{% trans "Thumbnail" %}</dt>
                    <dd><img src="{{ video.thumbnail.url }}" alt="{% trans 'Video thumbnail' %}" /></dd>
                    {% endif %}
                    <dt>{% trans "Filesize" %}</dt>
                    <dd>{% if filesize %}{{ filesize|filesizeformat }}{% else %}{% trans "File not found" %}{% endif %}</dd>
                    {% if video.duration %}
                    <dt>{% trans "Duration" %}</dt>
                    <dd>{{ video.formatted_duration }}</dd>
                    {% endif %}
                    <dt>{% trans "Usage" %}</dt>
                    <dd>
                        <a href="{{ video.usage_url }}">{% blocktrans count usage_count=video.get_usage.count %}Used {{ usage_count }} time{% plural %}Used {{ usage_count }} times{% endblocktrans %}</a>
                    </dd>
                </dl>
            </div>
        </div>
        <div class="row" style="margin-top: 2em;">
            <h2 class="u-text-transform-uppercase">{% trans "Transcodes" %}</h2>
            <p>{% trans "If you wish to generate HTML5 compliant transcodes use the form below. This may take a while depending on the length of the video." %}</p>
            {% if transcodes %}
            <h3 class="u-text-transform-uppercase">{% trans "Available Transcodes" %}</h3>
            <ul>
                {% for transcode in transcodes %}
                <li>
                    {% if transcode.file %}
                        <a href="{{ transcode.url }}" target="_blank">
                    {% endif %}
                        {% blocktrans with media_format=transcode.media_format quality=transcode.quality %}
                            {{ media_format }} ({{ quality }} quality)
                        {% endblocktrans %}
                    {% if transcode.file %}
                        </a>
                    {% endif %}
                    {% if transcode.processing %}
                        <span class="processing">{% trans "(Processing... hold tight)" %} </span>
                    {% endif %}
                    {% if transcode.error_message %}
                        <br/>
                        <span class="transcode-error">{% trans "ERROR:" %}</span>
                        <div class="transcode-error">
                            <pre>{{ transcode.error_message|format_error_message }}</pre>
                        </div>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            <h3 class="u-text-transform-uppercase">{% trans "Create transcode" %}</h3>
        {% if transcoder_installed and transcoder_enabled %}
            <form action="{% url 'wagtailvideos:create_transcode' video.id %}" method="POST">
                <ul class="fields">
                    {% csrf_token %}
                    <li>{% include "wagtailadmin/shared/field.html" with field=transcode_form.media_format li_classes="label-above label-uppercase" %}</li>
                    <li>{% include "wagtailadmin/shared/field.html" with field=transcode_form.quality li_classes="label-above label-uppercase" %}</li>
                    <li>
                        <input class="button" type="submit" value="{% trans 'Start' %}" />
                    </li>
                </ul>
            </form>
        {% elif transcoder_installed and not transcoder_enabled %}
            <br/><br/>
            <span class="transcode-error">{% trans "Transcoding is disabled." %}</span>
        {% elif not transcoder_installed and transcoder_enabled %}
            <br/><br/>
            <span class="transcode-error">{% trans "The selected transcoding backend is not installed on your server." %}</span>
        {% else %}
            <br/><br/>
            <span class="transcode-error">{% trans "The selected transcoding backend is not installed on your server and you have disabled transcodes. Please install the backend requirements and enable transcoding if you wish to transcode videos into an HTML5 video compliant format." %}</span>
        {% endif %}
        {% if tracks_action_url %}
            <h2 class="u-text-transform-uppercase">{% trans "Tracks" %}</h2>
            <p>{% trans 'You can add/edit subtitles or accessibility captions for this video. For information about the filetype that should be used see the mozilla docs on <a href="https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API">WebVTT</a>' %}</p>
                {% if video.track_listing %}
                <ul>
                {% for track in video.track_listing.tracks.all %}
                    <li>{{ track }}</li>
                {% endfor %}
                </ul>
                <a class="button" href="{{ tracks_action_url }}">{% trans "Edit" %}</a>
                {% else %}
                <a class="button" href="{{ tracks_action_url }}">{% trans "Add tracks" %}</a>
                {% endif %}
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

wagtailvideos/templates/wagtailvideos/videos/index.html
{% extends "wagtailadmin/generic/index.html" %}
{% load i18n %}

{% block titletag %}{% trans "Videos" %}{% endblock %}


{% block slim_header %}

{% trans "Add a video" as add_video_str %}
	{% include "wagtailadmin/shared/headers/slim_header.html" with title=video_str breadcrumbs_items=breadcrumbs_items icon_name="media" search_url=index_results_url search_form=search_form filters=filters  buttons=header_buttons only %}
{% endblock %}

wagtailvideos/templates/wagtailvideos/videos/results.html
{% extends "wagtailadmin/generic/index_results.html" %}
{% load wagtailadmin_tags %}
{% load i18n %}

{% block results %}
<div class="nice-padding">
    <ul class="listing horiz images">
        {% for video in videos %}
            <li>
                <a class="image-choice" href="{% url 'wagtailvideos:edit' video.id %}">
                    <figure>
                        {% if video.thumbnail %}
                            <img src="{{ video.thumbnail.url }}" height="165" width="165" class="show-transparency" alt="{% trans 'Video thumbnail' %}"/>
                        {% else %}
                            <img width="165" height="165" class="show-transparency" alt="" />
                        {% endif %}
                        <figcaption>{{ video.title|ellipsistrim:60 }}</figcaption>
                    </figure>
                </a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}
    

{% block no_results_message %}
    {% if is_searching %}
        <h2>{% blocktrans %}Sorry, no videos match "<em>{{ query_string }}</em>"{% endblocktrans %}</h2>
        {% search_other %}
    {% else %}
        {% url 'wagtailvideos:add_multiple' as wagtailvideos_add_video_url %}
        {% if current_collection %}
            <p>{% blocktrans %}You've not uploaded any videos in this collection. Why not <a href="{{ wagtailvideos_add_video_url }}">add one now</a>?{% endblocktrans %}</p>
        {% else %}
            <p>{% blocktrans %}You've not uploaded any videos. Why not <a href="{{ wagtailvideos_add_video_url }}">add one now</a>?{% endblocktrans %}</p>
        {% endif %}
    {% endif %}
{% endblock %}

wagtailvideos/templates/wagtailvideos/videos/usage.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans with title=video.title %}Usage of {{ title }}{% endblocktrans %}{% endblock %}
{% block content %}
    {% trans "Usage of" as usage_str %}
    {% include "wagtailadmin/shared/header.html" with title=usage_str subtitle=video.title %}

    <div class="nice-padding">
        <table class="listing">
            <col />
            <col width="30%"/>
            <col width="15%"/>
            <col width="15%"/>
            <thead>
                <tr>
                    <th class="title">{% trans "Title" %}</th>
                    <th>{% trans "Parent" %}</th>
                    <th>{% trans "Type" %}</th>
                    <th>{% trans "Status" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for page in used_by %}
                    <tr>
                        <td class="title" valign="top">
                            <h2><a href="{% url 'wagtailadmin_pages:edit' page.id %}" title="{% trans 'Edit this page' %}">{{ page.title }}</a></h2>
                        </td>
                        <td>
                            {% if page.get_parent %}
                                <a href="{% url 'wagtailadmin_explore' page.get_parent.id %}">{{ page.get_parent.title }}</a>
                            {% endif %}
                        </td>
                        <td>
                            {{ page.content_type.model_class.get_verbose_name }}
                        </td>
                        <td>
                            {% include "wagtailadmin/shared/page_status_tag.html" with page=page %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% include "wagtailadmin/shared/pagination_nav.html" with items=used_by linkurl="-" %}
{% endblock %}